Jdp221201 13
interceptor2048/project-jdp-2212-01 pull request #12
Opened 2022-11-22 22:56 UTC by MPawlow15

2022-11-23 17:42 UTC, interceptor2048 requested changes

2022-11-23 17:42 UTC, interceptor2048 commented on build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
Test discussion

2022-11-23 17:42 UTC, interceptor2048 commented on build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
Resolution

2022-11-23 17:43 UTC, interceptor2048 commented on build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
We agreed that it should look exactly as it looks

2022-11-23 17:43 UTC, interceptor2048 approved these changes, later dismissed

2022-11-25 09:41 UTC, julizale approved these changes
Jest ... git 🤣

2022-11-25 16:55 UTC, MichalRys90 approved these changes

2022-11-25 18:32 UTC, merged