Jdp221201 15
interceptor2048/project-jdp-2212-01 pull request #14
Opened 2022-11-25 07:01 UTC by MateuszCrono

2022-11-25 09:22 UTC, julizale requested changes
Hej Mateusz 👋 

1. Mam podejrzenie graniczące z pewnością :) że w encji User przydałoby się pole List < Order > inicjowane w momencie deklaracji ( na przykład  = new ArrayList<>(); ) opatrzone adnotacją:
@OneToMany(targetEntity = Order.class,
            mappedBy = "user",
            cascade = CascadeType.ALL,
            fetch = FetchType.LAZY)
Dzięki temu, relacja między naszymi encjami User i Order stanie się faktem 😉 (może być oczywiście inna kolekcja niekoniecznie lista)

2. Podejrzewam, że będą potrzebne settery w encji User. Sam długo się trzymałem, żeby nie dodawać, bo gdzieś w kursie wpojono mi, że settery to zło :), ale w końcu musiałem się złamać przy robieniu testów i zacząłem używać adnotacji @Data podpatrzonej u Michała (adnotacja z Lomboka, która robi wszystko oprócz konstruktorów i smażenia placków :D )
W tej klasie dodatkowo będzie potrzeba ustawiania blokowania usera, więc chyba bez settera się nie obędzie.

3. Chyba przez pomyłkę utworzył Ci się moduł project-jdp-2212-01

To że się tak rozpisałem, to nie znaczy że jest źle, bo jest dobrze 👍 tylko ćwiczę pisanie review :D

2022-11-25 10:01 UTC, MichalRys90 approved these changes

2022-11-25 10:05 UTC, MichalRys90 reviewed
Zgadzam się z Julianem, ale jako że już rozpoczęliście dyskusje i musi być ona rozstrzygnięta to pozwolę sobie zatwierdzić :)

2022-11-28 05:57 UTC, MateuszCrono commented
> Hej Mateusz 👋
> 
> 1. Mam podejrzenie graniczące z pewnością :) że w encji User przydałoby się pole List < Order > inicjowane w momencie deklaracji ( na przykład  = new ArrayList<>(); ) opatrzone adnotacją:
>    @OneToMany(targetEntity = Order.class,
>    mappedBy = "user",
>    cascade = CascadeType.ALL,
>    fetch = FetchType.LAZY)
>    Dzięki temu, relacja między naszymi encjami User i Order stanie się faktem 😉 (może być oczywiście inna kolekcja niekoniecznie lista)
> 2. Podejrzewam, że będą potrzebne settery w encji User. Sam długo się trzymałem, żeby nie dodawać, bo gdzieś w kursie wpojono mi, że settery to zło :), ale w końcu musiałem się złamać przy robieniu testów i zacząłem używać adnotacji @DaTa podpatrzonej u Michała (adnotacja z Lomboka, która robi wszystko oprócz konstruktorów i smażenia placków :D )
>    W tej klasie dodatkowo będzie potrzeba ustawiania blokowania usera, więc chyba bez settera się nie obędzie.
> 3. Chyba przez pomyłkę utworzył Ci się moduł project-jdp-2212-01
> 
> To że się tak rozpisałem, to nie znaczy że jest źle, bo jest dobrze 👍 tylko ćwiczę pisanie review :D

Hej Julian, dzieki za code review, zgadzam sie z wszystkimi propozycjami. Kod Poprawiony zgodnie z twoimi sugestiami i zupdejtowane pod obecny master branch

2022-11-28 05:57 UTC, closed without merging