Jdp221201 21
interceptor2048/project-jdp-2212-01 pull request #27
Opened 2022-12-02 01:01 UTC by rafalglodek

2022-12-02 01:04 UTC, rafalglodek commented
Prosze o review.

2022-12-02 01:31 UTC, MPawlow15 approved these changes

2022-12-02 06:09 UTC, MichalRys90 requested changes
Hej, wydaje mi się, że ProductDto powinien zostać w poprzedniej postaci. Składa się on z pól które mamy zwracać według założeń projektu.

2022-12-04 07:17 UTC, MichalRys90 approved these changes

2022-12-05 01:00 UTC, merged