Jdp221201 1
interceptor2048/project-jdp-2212-01 pull request #9
Opened 2022-11-20 19:09 UTC by rafalglodek

Initial implementation of Product Controller

2022-11-20 19:19 UTC, MichalRys90 approved these changes

2022-11-21 08:51 UTC, MichalRys90 reviewed
Zatwierdziłem żeby nasz projekt zaczął w końcu powstawać. Będzie problem z testowaniem. getProduct, deleteProduct i updateProduct są na tym samym endpoincie dlatego w odpowiedzi otrzymamy błąd. To samo dotyczy createProduct oraz getProducts.

2022-11-21 22:39 UTC, julizale requested changes
Hej Rafał, robiłem testy postmanem, wszystko śmiga elegancko. Napisałem Ci komentarz do linii 28 w GroupController, jeżeli uważasz tak samo jak ja to proszę zmień. :)

2022-11-21 22:39 UTC, julizale commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    @PutMapping(value = "{groupId}")
Wydaje mi się że ta metoda oprócz id produktu w nagłówku, powinna dostawać w body również jsona ze zmienionym produktem:
 @PutMapping(value = "{productId}", consumes = MediaType.APPLICATION_JSON_VALUE)

2022-11-23 20:55 UTC, julizale commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    @PutMapping(value = "{groupId}")
W sumie, to można to zrobić na etapie właściwej implementacji kontrolera. Oznaczam dyskusję jako resolved, żeby nam się ten projekt budował :)

2022-11-23 20:57 UTC, julizale approved these changes

2022-11-24 10:57 UTC, MateuszCrono commented
Rafał Potrzebujemy rozwiazać Konflikt twojego brancha z Masterem, przed pullem

2022-11-26 19:48 UTC, closed without merging